"""
PDF Generator — DataPilot AI
Professional business report PDF with proper markdown rendering.
"""
import re
from fpdf import FPDF

# ── Page geometry ────────────────────────────────────────────────────────────
LEFT_MARGIN   = 18
RIGHT_MARGIN  = 18
TOP_MARGIN    = 28
BOTTOM_MARGIN = 20

# ── Colours (R, G, B) ────────────────────────────────────────────────────────
C_INDIGO      = (79,  70,  229)
C_INDIGO_SOFT = (99,  102, 241)
C_SLATE_DARK  = (30,  41,  59)
C_SLATE_MID   = (71,  85,  105)
C_SLATE_LIGHT = (148, 163, 184)
C_WHITE       = (255, 255, 255)
C_BG_LIGHT    = (248, 250, 252)


def _clean(text: str) -> str:
    """Strip markdown syntax and replace unicode symbols with ASCII equivalents."""
    # Remove bold/italic markers: **text** → text, *text* → text
    text = re.sub(r'\*{2}([^*]+)\*{2}', r'\1', text)
    text = re.sub(r'\*([^*]+)\*',       r'\1', text)
    # Remove inline code
    text = re.sub(r'`([^`]*)`', r'\1', text)

    # Unicode → ASCII replacements
    REPLACE = {
        "\u202f": " ", "\u200b": "",  "\xa0":   " ",
        "\u2013": "-", "\u2014": "--",
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2022": "-", "\u2026": "...",
        "\u2122": "TM", "\u00ae": "(R)", "\u00a9": "(C)",
        "\u2714": "Yes", "\u2716": "No", "\u27a1": "->",
        "\u2019": "'",
        # Emoji strip
        "✨": "", "📄": "", "🤖": "", "📌": "", "✅": "", "❌": "",
        "📊": "", "📈": "", "📉": "", "💡": "", "⚠️": "",
    }
    for orig, rep in REPLACE.items():
        text = text.replace(orig, rep)

    # Encode to latin-1, replacing anything still unmappable
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _bold_parts(text: str):
    """
    Split a line into (is_bold, segment) tuples by parsing **...** markers
    *before* stripping them, so we can toggle bold font in FPDF.
    """
    parts = []
    pattern = re.compile(r'\*{2}([^*]+)\*{2}')
    last = 0
    for m in pattern.finditer(text):
        if m.start() > last:
            parts.append((False, text[last:m.start()]))
        parts.append((True, m.group(1)))
        last = m.end()
    if last < len(text):
        parts.append((False, text[last:]))
    return parts


class ReportPDF(FPDF):
    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_margins(LEFT_MARGIN, TOP_MARGIN, RIGHT_MARGIN)
        self.set_auto_page_break(auto=True, margin=BOTTOM_MARGIN)

    def header(self):
        # Indigo accent bar across the top
        self.set_fill_color(*C_INDIGO)
        self.rect(0, 0, 210, 10, "F")

        # Logo text
        self.set_xy(LEFT_MARGIN, 12)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_INDIGO_SOFT)
        self.cell(0, 6, "DATAPILOT AI  |  BUSINESS INTELLIGENCE REPORT", ln=False)

        # Thin separator line
        self.set_draw_color(*C_INDIGO_SOFT)
        self.set_line_width(0.3)
        self.line(LEFT_MARGIN, 20, 210 - RIGHT_MARGIN, 20)
        self.ln(6)

    def footer(self):
        self.set_y(-14)
        self.set_draw_color(*C_SLATE_LIGHT)
        self.set_line_width(0.2)
        self.line(LEFT_MARGIN, self.get_y(), 210 - RIGHT_MARGIN, self.get_y())
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*C_SLATE_LIGHT)
        self.cell(0, 6, f"Confidential  |  Page {self.page_no()}/{{nb}}  |  Generated by DataPilot AI", align="C")


# ─────────────────────────────────────────────────────────────────────────────
# Inline bold writer — renders a single paragraph with mixed bold/normal runs
# ─────────────────────────────────────────────────────────────────────────────
def _write_inline(pdf: ReportPDF, raw_line: str, line_h: float, base_size: int):
    """Write a line that may contain **bold** segments, using write() for flow."""
    parts = _bold_parts(raw_line)
    for is_bold, segment in parts:
        segment = _clean(segment)
        if not segment:
            continue
        style = "B" if is_bold else ""
        pdf.set_font("Helvetica", style, base_size)
        pdf.write(line_h, segment)
    pdf.ln(line_h)


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────
def convert_markdown_to_pdf(markdown_text: str) -> bytes:
    """
    Convert a markdown business report string into a polished PDF.
    Properly parses ## headings, **bold**, - bullet lists, and plain paragraphs.
    """
    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    usable_w = 210 - LEFT_MARGIN - RIGHT_MARGIN   # ~174 mm

    lines = markdown_text.split("\n")
    i = 0
    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()

        # ── Skip empty lines ──────────────────────────────────────────────────
        if not stripped:
            pdf.ln(3)
            i += 1
            continue

        # ── H1  # Title ───────────────────────────────────────────────────────
        if stripped.startswith("# ") and not stripped.startswith("## "):
            text = _clean(stripped[2:].strip())
            pdf.set_font("Helvetica", "B", 20)
            pdf.set_text_color(*C_INDIGO)
            pdf.set_fill_color(*C_BG_LIGHT)
            pdf.multi_cell(usable_w, 10, text, align="L")
            pdf.ln(4)

        # ── H2  ## Section ────────────────────────────────────────────────────
        elif stripped.startswith("## "):
            text = _clean(stripped[3:].strip())
            pdf.ln(4)
            # Indigo left bar decoration
            x, y = pdf.get_x(), pdf.get_y()
            pdf.set_fill_color(*C_INDIGO)
            pdf.rect(LEFT_MARGIN - 4, y, 3, 8, "F")
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(*C_INDIGO)
            pdf.cell(usable_w, 8, text, ln=True)
            # Underline
            pdf.set_draw_color(*C_INDIGO_SOFT)
            pdf.set_line_width(0.2)
            y2 = pdf.get_y()
            pdf.line(LEFT_MARGIN, y2, LEFT_MARGIN + usable_w, y2)
            pdf.ln(4)

        # ── H3  ### Sub-section ───────────────────────────────────────────────
        elif stripped.startswith("### "):
            text = _clean(stripped[4:].strip())
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*C_INDIGO_SOFT)
            pdf.cell(usable_w, 7, text, ln=True)
            pdf.ln(1)

        # ── Bullet  - item  or  * item ────────────────────────────────────────
        elif stripped.startswith("- ") or stripped.startswith("* "):
            body = stripped[2:].strip()
            pdf.set_text_color(*C_SLATE_DARK)
            pdf.set_font("Helvetica", "", 9)

            # Draw bullet circle
            bx = LEFT_MARGIN + 3
            by = pdf.get_y() + 2.5
            pdf.set_fill_color(*C_INDIGO_SOFT)
            pdf.ellipse(bx, by, 1.5, 1.5, "F")

            # Write text with indent, supporting inline bold
            pdf.set_x(LEFT_MARGIN + 7)
            bullet_w = usable_w - 7
            parts = _bold_parts(body)
            # Use multi_cell for wrapping; flatten bold for now (multi_cell doesn't support mixed)
            full_text = _clean(body)
            pdf.multi_cell(bullet_w, 5.5, full_text, align="L")
            pdf.ln(1)

        # ── Numbered list  1. item ────────────────────────────────────────────
        elif re.match(r'^\d+\.\s', stripped):
            m = re.match(r'^(\d+)\.\s+(.*)', stripped)
            num  = m.group(1)
            body = _clean(m.group(2).strip())
            pdf.set_text_color(*C_SLATE_DARK)
            pdf.set_font("Helvetica", "B", 9)
            # Number
            pdf.set_x(LEFT_MARGIN + 2)
            pdf.cell(5, 5.5, f"{num}.", ln=False)
            # Body
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(LEFT_MARGIN + 7)
            pdf.multi_cell(usable_w - 7, 5.5, body, align="L")
            pdf.ln(1)

        # ── Horizontal rule  --- or === ───────────────────────────────────────
        elif re.match(r'^[-=]{3,}$', stripped):
            pdf.set_draw_color(*C_SLATE_LIGHT)
            pdf.set_line_width(0.2)
            pdf.line(LEFT_MARGIN, pdf.get_y(), LEFT_MARGIN + usable_w, pdf.get_y())
            pdf.ln(4)

        # ── Plain paragraph ───────────────────────────────────────────────────
        else:
            pdf.set_text_color(*C_SLATE_DARK)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_x(LEFT_MARGIN)
            # Render inline bold within paragraph
            _write_inline(pdf, stripped, 5.5, 10)
            pdf.ln(1)

        i += 1

    return bytes(pdf.output())
